# app.yaml - Google App Engine Configuration
runtime: python39

# Environment variables for your AI Recipe + Grocery Delivery App
# SECURITY WARNING: NEVER commit real API keys to version control!
# Use Google Secret Manager or set these during deployment
env_variables:
  # Database Configuration
  MONGO_URL: "YOUR_MONGODB_ATLAS_CONNECTION_STRING"  # Replace with MongoDB Atlas connection string
  DB_NAME: "buildyoursmartcart_production"
  
  # OpenAI API Configuration
  OPENAI_API_KEY: "YOUR_OPENAI_API_KEY"  # Replace with your actual OpenAI API key
  
  # Walmart API Configuration
  WALMART_CONSUMER_ID: "YOUR_WALMART_CONSUMER_ID"  # Replace with your actual Walmart Consumer ID
  WALMART_KEY_VERSION: "1"
  WALMART_PRIVATE_KEY: "YOUR_WALMART_PRIVATE_KEY"  # Replace with your actual Walmart private key
  
  # Mailjet Email Service Configuration
  MAILJET_API_KEY: "YOUR_MAILJET_API_KEY"  # Replace with your actual Mailjet API key
  MAILJET_SECRET_KEY: "YOUR_MAILJET_SECRET_KEY"  # Replace with your actual Mailjet secret key
  SENDER_EMAIL: "YOUR_SENDER_EMAIL@example.com"  # Replace with your actual sender email
  
  # Stripe Configuration
  STRIPE_API_KEY: "YOUR_STRIPE_API_KEY"  # Replace with your actual Stripe API key
  
  # JWT Secret Key
  SECRET_KEY: "YOUR_STRONG_RANDOM_JWT_SECRET"  # Generate a strong, random secret key

# Route handlers
handlers:
  # Direct all traffic to your main.py application
  - url: /.*
    script: auto

# Automatic scaling configuration
automatic_scaling:
  min_instances: 0  # Allow scaling down to zero to save costs
  max_instances: 3  # Max instances to handle traffic spikes
  target_cpu_utilization: 0.6
  target_throughput_utilization: 0.6

# Resources allocation
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10