# app.yaml - Google App Engine Configuration
# This file is ready for Google Cloud deployment
# Set all environment variables through Google Cloud Console → Variables & Secrets
runtime: python39

# Environment variables will be set through Google Cloud Console
# Go to: Cloud Run → [Your Service] → Edit Container → Variables & Secrets
env_variables:
  # Database Configuration
  MONGO_URL: "mongodb://localhost:27017"  # Set your MongoDB Atlas connection string in Google Cloud
  DB_NAME: "buildyoursmartcart_production"
  
  # OpenAI API Configuration
  OPENAI_API_KEY: "your-openai-api-key"  # Set your OpenAI API key in Google Cloud
  
  # Walmart API Configuration
  WALMART_CONSUMER_ID: "your-walmart-consumer-id"  # Set your Walmart Consumer ID in Google Cloud
  WALMART_KEY_VERSION: "1"
  WALMART_PRIVATE_KEY: "your-walmart-private-key"  # Set your Walmart private key in Google Cloud
  
  # Mailjet Email Service Configuration
  MAILJET_API_KEY: "your-mailjet-api-key"  # Set your Mailjet API key in Google Cloud
  MAILJET_SECRET_KEY: "your-mailjet-secret-key"  # Set your Mailjet secret key in Google Cloud
  SENDER_EMAIL: "your-sender-email@example.com"  # Set your sender email in Google Cloud
  
  # Stripe Configuration
  STRIPE_API_KEY: "your-stripe-api-key"  # Set your Stripe API key in Google Cloud
  
  # JWT Secret Key
  SECRET_KEY: "your-jwt-secret-key"  # Set a strong, random secret key in Google Cloud

# Route handlers
handlers:
  # Direct all traffic to your main.py application
  - url: /.*
    script: auto

# Automatic scaling configuration
automatic_scaling:
  min_instances: 0  # Allow scaling down to zero to save costs
  max_instances: 3  # Max instances to handle traffic spikes
  target_cpu_utilization: 0.6
  target_throughput_utilization: 0.6

# Resources allocation
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10